import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Toaster } from "react-hot-toast";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FileFlex",
  description: "Generated by Pratham Shirbhate",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      

      <body className={inter.className}>
      <div className="w-full flex justify-between items-center p-6 bg-green-100 shadow-md">
        <Link href='/'>
        <div className="flex items-center space-x-2">
          <Image src="/logo.png" alt="Logo" width={50} height={50} />
          <span className="text-2xl font-bold">FileFlex</span>
        </div>
        </Link>
        <Link href='https://www.linkedin.com/in/prathamshirbhate' legacyBehavior>
         <a target="_blank"rel="noopener noreferrer">
        <div>
          <Image
            src="/linkedin.png"
            alt="Avatar"
            width={40}
            height={40}
            className="rounded cursor-pointer hover:scale-125 transition-all"
          />
        </div>
        </a>
        </Link>
      </div>
      <Toaster position="top-right" />
      
      {children}
      <footer className="w-full p-4 shadow-md text-center">
        <p className=" text-2xl font-serif">
          Made by <span className="font-pacifico ">Pratham Shirbhate</span>
        </p>
      </footer>
      </body>
      
    </html>
  );
}
